debug: false

server:
  port: 8097

spring:
  application:
    name: spring-boot-kafka
  cache:
    cache-names:

kafka:
  config:
    test-group00:
      bootstrap-servers: kafka1,kafka2,kafka3
      topics: test-topic
      processor: zhyyy
      count: 4
