debug: false

server:
  port: 8087

spring:
  application:
    name: spring-boot-test
  cache:
    type: CAFFEINE
    caffeine:
      spec: initialCapacity=1048576,maximumSize=1073741824,expireAfterAccess=10m
