debug: false

server:
  port: 8087

spring:
  application:
    name: spring-boot-schedule
  task:
    scheduling:
      pool:
        size: 1
    execution:
      pool:
        core-size: 2
  quartz:
    startupDelay: 10000 #这里是毫秒值

