debug: false

server:
  port: 8087

spring:
  application:
    name: spring-boot-database

datasource:
  write:
    driver: org.h2.Driver
    url: jdbc:h2:mem:worker-write
    validation-query: select 1
  read:
    driver: org.h2.Driver
    url: jdbc:h2:mem:worker-read
    validation-query: select 1
